#!/bin/sh

REPO_VERSION="r$(hg id -n)"
VERSION=$1
if test -z "$VERSION"; then
	echo "missing version"
	exit 2
fi

echo "Building version $VERSION (repo version $REPO_VERSION)"

xcodebuild -scheme archive -configuration Release VERSION=$VERSION REPO_VERSION=$REPO_VERSION || exit

TMPDMG=vico-tmp.dmg
/bin/rm -f $TMPDMG

die()
{
    echo "$1"
    /bin/rm -f $TMPDMG
    exit 1
}

APP=build/Release/Vico.app

echo "Stripping binary"
strip $APP/Contents/MacOS/*

VOL="vico-$VERSION"
DMG="$VOL.dmg"
echo "Creating disk image $VOL"

# clean up if we're interrupted
trap 'die Interrupted' 2 3 15

# Create the source folder and copy the application there.
DMG_SOURCE="Vico $VERSION"
mkdir "$DMG_SOURCE" || die "failed to create .dmg source folder"
/bin/cp -R $APP "$DMG_SOURCE" || die "failed to copy application to the .dmg source folder"
ln -s /Applications "$DMG_SOURCE/Applications"

# Create a disk image of the source folder and compress it.
hdiutil makehybrid -o "$TMPDMG" "$DMG_SOURCE" -hfs
hdiutil convert -format UDBZ "$TMPDMG" -o "$DMG"

/bin/rm -f $TMPDMG
ls -lh "$DMG"

