#!/bin/sh

REPO_VERSION=$(hg id -n)
VERSION=$1
if test -z "$VERSION"; then
	echo "missing version"
	exit 2
fi

echo "Building vibrant version $VERSION (repo version $REPO_VERSION)"

xcodebuild -project vibrant.xcodeproj -target Vibrant -configuration Release build VERSION=$VERSION REPO_VERSION=$REPO_VERSION || exit

TMPDMG=vibrant-tmp.dmg
/bin/rm -f $TMPDMG

die()
{
    echo "$1"
    test -n "$MYDEV" && hdiutil eject $MYDEV
    /bin/rm -f $TMPDMG
    exit 1
}

APP=build/Release/Vibrant.app

echo "Stripping binary"
strip $APP/Contents/MacOS/Vibrant

VOL="Vibrant-$VERSION"
DMG=$VOL.dmg
echo "Creating disk image $VOL"

# clean up if we're interrupted
trap 'rm -f $TMPDMG; exit 1' 2 3 15

# create a disk image
hdiutil create -megabytes 10 $TMPDMG -layout NONE
# Attach a device with this but don't mount it
MYDEV=`hdid -nomount $TMPDMG`
test -n "$MYDEV" || die "failed to attach disk image"
# create a file system
newfs_hfs -v "$VOL" $MYDEV || die "failed to create file system"
# Detach device
hdiutil eject $MYDEV
# mount it
hdid $TMPDMG || die "failed to mount disk image"

root="/Volumes/$VOL"

# copy stuff to the disk image
/bin/cp -R $APP "$root" || die "failed to copy application to disk image"

ln -s /Applications $root/Applications

rm -f $DMG

hdiutil eject $MYDEV
# compress it and make it read only
hdiutil convert -format UDZO $TMPDMG -o $DMG
/bin/rm -f $TMPDMG
ls -lh $DMG

#### Create and sign a zip file for automatic updates.

BASE="http://bzero.se/vibrant"
ZIP=$VOL.zip
ditto -ck --keepParent "$APP" "$ZIP"

SIZE=$(stat -f %z "$ZIP")
SIGNATURE=$(/usr/bin/openssl dgst -sha1 -binary < $ZIP | /usr/bin/openssl dgst -dss1 -sign sparkle_priv.pem | /usr/bin/openssl enc -base64)

cat > $VOL.xml <<EOF
<item>
    <title>Version $VERSION</title>
    <sparkle:releaseNotesLink>
        $BASE/version-$VERSION.html
    </sparkle:releaseNotesLink>
    <pubDate>$(LC_TIME=en_US date +"%a, %d %b %G %T %z")</pubDate>
    <enclosure url="$BASE/$ZIP"
               sparkle:version="$REPO_VERSION"
               sparkle:shortVersionString="$VERSION"
               sparkle:dsaSignature="$SIGNATURE"
               length="$SIZE"
               type="application/octet-stream" />
</item>
EOF
cat $VOL.xml

echo "scp $DMG bzero.se:/var/www/htdocs/bzero.se/vibrant"
echo "scp $ZIP bzero.se:/var/www/htdocs/bzero.se/vibrant"

