#!/bin/sh

head()
{
	file=$1
	title=$2

cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">

<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="help.css" type="text/css" media="screen">
  <title>$title</title>
</head>
<body>
EOF
}

tail()
{
	cat <<EOF
</body>
</html>
EOF
}

while test -n "$1"; do
	file=$1
	title=$(sed -n '/^# /{s///;p;q;}' "$1")
	echo "converting $file with title '$title'" >&2
	(head "$file" "$title"
	 perl $HOME/bin/Markdown.pl --html4tags "$file"
	 tail) > "$(basename "${file%.*}.html")"
	shift
done

